# Generated by Django 4.0.3 on 2022-08-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_qarzdor_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qarzdor',
            name='phone',
        ),
        migrations.AddField(
            model_name='qarzdorlar',
            name='phone',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
