# Generated by Django 4.0.3 on 2022-08-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_remove_qarzdor_phone_qarzdorlar_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qarzdorlar',
            name='phone',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
